#!/bin/bash

set -e
. /usr/share/debconf/confmodule

case "$1" in
  configure)
    sed -i -e "s/\(^rpcpassword\)\(.*\)/rpcpassword=$(pwgen 64 1)/" /var/lib/emc/.Paris/Paris.conf
    chmod 600 /var/lib/emc/.Paris/Paris.conf
    chown -R emc.emc /var/lib/emc/.Paris
    mkdir -p /etc/Paris
    ln -sf /var/lib/emc/.Paris/Paris.conf /etc/Paris/Paris.conf || true
    ln -sf /etc/ssl/emc /etc/Paris/certs || true
    systemctl daemon-reload
    [ -f /var/tmp/Paris-install.flag ] && {
      rm -f /var/tmp/Paris-install.flag
      systemctl enable Parisd
    }
    systemctl status Parisd >/dev/null 2>&1 && systemctl restart Parisd || {
      systemctl is-enabled Parisd >/dev/null 2>&1 && systemctl start Parisd || true
    }
  ;;
esac

exit 0
