#!/bin/bash

set -e
. /usr/share/debconf/confmodule

case "$1" in
  install)
    getent passwd emc >/dev/null || {
      mkdir /tmp/emcskel
      groupadd emc
      useradd -m -d /var/lib/emc -k /tmp/emcskel -s /bin/false -g emc emc
      rmdir /tmp/emcskel
    }
    [ ! -f /etc/ssl/emc/Paris.key ] || [ ! -f /etc/ssl/emc/Paris.crt ] && {
      mkdir -p /etc/ssl/emc
      openssl req -nodes -x509 -newkey rsa:4096 -keyout /etc/ssl/emc/Paris.key -out /etc/ssl/emc/Paris.crt -days 3560 -subj /C=CY/L=Nicosia/O=Paris/CN=Paris.emc
      chown emc.emc /etc/ssl/emc/Paris.key /etc/ssl/emc/Paris.crt
      chmod 600 /etc/ssl/emc/Paris.key
    }
    touch /var/tmp/Paris-install.flag
  ;;
esac

[ -f /var/lib/emc/.Paris/Paris.conf ] && sed -i -e 's|rpcallowip=\*|rpcallowip=0.0.0.0/0|' /var/lib/emc/.Paris/Paris.conf || true
[ -f /var/lib/emc/.Paris/addr.dat ] && { 
  systemctl status Parisd >/dev/null 2>&1 && systemctl stop Parisd >/dev/null 2>&1 || true
  cd /var/lib/emc/.Paris && rm -rf database addr.dat nameindex* blk* *.log .lock
} || true

exit 0
