#!/bin/bash

set -e
. /usr/share/debconf/confmodule

case "$1" in
  remove|deconfigure|abort-install)
    rm -f /var/tmp/Paris-install.flag
    systemctl is-enabled Parisd >/dev/null && systemctl disable Parisd >/dev/null || true
    systemctl status Parisd >/dev/null && systemctl stop Parisd >/dev/null || true
    pkill -9 -u emc > /dev/null 2>&1 || true
    getent passwd emc >/dev/null && userdel emc >/dev/null 2>&1 || true
    rm -f /etc/ssl/emc/Paris.key /etc/ssl/emc/Paris.crt /etc/Paris/Paris.conf /etc/Paris/certs
  ;;
esac

exit 0
