#!/bin/bash

getent passwd emc >/dev/null || {
  mkdir /tmp/emcskel
  groupadd emc
  useradd -m -d /var/lib/emc -k /tmp/emcskel -s /bin/false -g emc emc
  rmdir /tmp/emcskel
}

mkdir -p /etc/ssl/emc
[ ! -f /etc/ssl/emc/Paris.key ] || [ ! -f /etc/ssl/emc/Paris.crt ] && openssl req -nodes -x509 -newkey rsa:4096 -keyout /etc/ssl/emc/Paris.key -out /etc/ssl/emc/Paris.crt -days 3560 -subj /C=US/ST=Oregon/L=Portland/O=IT/CN=Paris.emc

[ -f /var/lib/emc/.Paris/addr.dat ] && { cd /var/lib/emc/.Paris && rm -rf database addr.dat nameindex* blk* *.log .lock; }
[ -f /var/lib/emc/.Paris/Paris.conf ] && { 
  sed -i -e 's|rpcallowip=\*|rpcallowip=0.0.0.0/0|' /var/lib/emc/.Paris/Paris.conf
  service Parisd status >/dev/null && service Parisd restart >/dev/null
  exit 0
}

mkdir -p /etc/logrotate.d
cat<<EOF > /etc/logrotate.d/Parisd
/var/lib/emc/.Paris/*.log
{
  weekly
  rotate 6
  compress
  delaycompress
  missingok
  create 0644 emc emc
}
EOF

mkdir -p /var/lib/emc/.Paris
cat<<EOF >/var/lib/emc/.Paris/Paris.conf
rpcuser=emccoinrpc
rpcpassword=`pwgen 50 1`
listen=1
server=1
rpcallowip=127.0.0.1
rpcport=6662
maxconnections=80
gen=0
daemon=1
rpcssl=1
rpcsslcertificatechainfile=/etc/ssl/emc/Paris.crt
rpcsslprivatekeyfile=/etc/ssl/emc/Paris.key
rpcsslciphers=HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4:!SSLv2
EOF

chmod 600 /var/lib/emc/.Paris/Paris.conf
chown -R emc.emc /var/lib/emc/.Paris

mkdir -p /etc/Paris
ln -s /var/lib/emc/.Paris/Paris.conf /etc/Paris/Paris.conf
ln -s /etc/ssl/emc /etc/Paris/certs

update-rc.d Parisd defaults
service Parisd start

exit 0
